name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - 'xmas-widget.js'
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache for xmas-widget.js
        run: |
          echo "Purging jsDelivr cache..."
          curl -X GET "https://purge.jsdelivr.net/gh/negtvozero-jpg/XmasLights/xmas-widget.js"
